version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6

  auth-service:
    build: ./services/auth
    environment:
      - DATABASE_URL=postgresql://user:password@postgres/taskdb
      - SECRET_KEY=your-secret-key
    depends_on:
      - postgres

  task-service:
    build: ./services/tasks
    environment:
      - DATABASE_URL=postgresql://user:password@postgres/taskdb
      - NOTIFICATION_SERVICE_URL=http://notification-service:8000
    depends_on:
      - postgres
      - notification-service

  project-service:
    build: ./services/projects
    environment:
      - DATABASE_URL=postgresql://user:password@postgres/taskdb
      - NOTIFICATION_SERVICE_URL=http://notification-service:8000
    depends_on:
      - postgres
      - notification-service

  notification-service:
    build: ./services/notifications
    environment:
      - DATABASE_URL=postgresql://user:password@postgres/taskdb
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8000
      - TASK_SERVICE_URL=http://task-service:8000
      - PROJECT_SERVICE_URL=http://project-service:8000
    depends_on:
      - auth-service
      - task-service
      - project-service
      - notification-service

  celery-worker:
    build:
      context: ./services/notifications
      dockerfile: celery_worker.dockerfile
    environment:
      - DATABASE_URL=postgresql://user:password@postgres/taskdb
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data: