global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8000']

  - job_name: 'task-service'
    static_configs:
      - targets: ['task-service:8000']

  - job_name: 'project-service'
    static_configs:
      - targets: ['project-service:8000']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8000']
